### ISSUE TITLE
net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by drtanzil** [ardhityawiedhairawan/AndroidSplashScreen#1]
telephone, email etc. hyperlink not working. onClick showing net::ERR_UNKNOWN_URL_SCHEME error

**Comment by ardhityawiedhairawan** [comment]
Hi, 
I add functionality to open hyperlink likes Telephone, Email and .pdf. You can used Callback method that I added. Please update your source. 

Thank you.

**Comment by Tech-Nur** [comment]
I have simple solution for this problem..

**Comment by Tech-Nur** [comment]
`

 @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url ) {
            // TODO Auto-generated method stub
             if (url.startsWith("mailto:") || url.startsWith("tel:")) {
             Intent intent = new Intent(Intent.ACTION_VIEW,
             Uri.parse(url));
             startActivity(intent);
             view.loadUrl(url);
             return true;
            }
}

`

**Comment by ardhityawiedhairawan** [comment]
I had updated the source. Thank you for the solution.
